name: cosmos_codec
version: 0.0.2

dependencies:
  alan: ^0.40.2+1
  convert: ^2.1.1
  pointycastle: ^1.0.2
  quiver: ^2.1.5
  # typed_data: ^1.2.0

dev_dependencies: 
  meta: 1.3.0
  test: 1.16.5

environment:
  sdk: ">=1.19.0 <3.0.0"
