name: cosmos_codec
version: 2.0.0

dependencies:
  alan: ^0.41.2+1
  convert: ^3.0.0
  pointycastle: ^3.6.0
  quiver: ^3.1.0
  # typed_data: ^1.2.0

dev_dependencies: 
  meta: ^1.3.0
  test: ^1.16.5

environment:
  sdk: ">=2.12.0 <3.0.0"
